# © 2022 Nokia.
#
# This code is a Contribution to the gNMIc project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0.
# No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose.
# This code is provided on an “as is” basis without any warranties of any kind.
#
# SPDX-License-Identifier: Apache-2.0

version: '3' 

networks:
  gnmic-net:
    driver: bridge

services:
  gnmic1:
    image: ghcr.io/openconfig/gnmic:latest
    container_name: gnmic1
    volumes:
      - ./gnmic1.yaml:/app/gnmic.yaml
    command: "subscribe --config /app/gnmic.yaml"
    networks:
      - gnmic-net
    depends_on:
      - kafka-server
      
  kafka-server:
    image: 'bitnami/kafka:latest'
    container_name: kafka-server
    networks:
      - gnmic-net
    ports:
      - "9092:9092"
      - "9000:9000"
    environment:
      - KAFKA_CFG_ZOOKEEPER_CONNECT=zookeeper-server:2181
      - KAFKA_CFG_ADVERTISED_LISTENERS=PLAINTEXT://kafka-server:9092
      - ALLOW_PLAINTEXT_LISTENER=yes
      - JMX_PORT=9000
    depends_on:
      - zookeeper-server

  zookeeper-server:
    image: 'bitnami/zookeeper:latest'
    container_name: zk-server
    networks:
      - gnmic-net
    ports:
      - "2181:2181"
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      