# © 2022 Nokia.
#
# This code is a Contribution to the gNMIc project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0.
# No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose.
# This code is provided on an “as is” basis without any warranties of any kind.
#
# SPDX-License-Identifier: Apache-2.0

username: admin
password: sros
port: 57400
timeout: 5s
skip-verify: true
tls-key: /path/to/client.key
tls-cert: /path/to/client.crt
tls-ca: /path/to/ca.crt

targets:
  172.17.0.100:
    timeout: 2s
    subscriptions:
      - sub1
    outputs:
      - output1
      - output3
  172.17.0.101:
    username: sros
    password: sros
    insecure: true
    subscriptions:
      - sub2
    outputs:
      - output2
      - output3
  172.17.0.102:57000:
    password: sros123
    tls-key: /path/file1
    tls-cert: /path/file2
  172.17.0.103:
    
subscriptions:
  sub1:
    paths:
      - /configure/port[port-id=*]
      - /state/port[port-id=*]
    stream-mode: on_change # target-defined # sample
  sub2:
    paths:
       - /configure/port[port-id=*]/statistics
    stream-mode: sample
    sample-interval: 10s

outputs:
  output1:
    type: file
    file-type: stdout
  output2:
    type: file
    filename: local.log
  output3:
    type: nats
    address: localhost:4222
    subject-prefix: telemetry
    username:
    password:
  output4:
    type: stan
    address: localhost:4223
    subject: telemetry
    username:
    password:
    name: 
    cluster-name: test-cluster
    timeout:
    ping-interval:
    ping-retry:
  output5:
    type: kafka
    address: localhost:9092
    topic: telemetry
    max-retry: 
    timeout:
  output6:
    type: nats
    address: localhost:4222
    subject-prefix: telemetry
    username:
    password:
