# © 2022 Nokia.
#
# This code is a Contribution to the gNMIc project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0.
# No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose.
# This code is provided on an “as is” basis without any warranties of any kind.
#
# SPDX-License-Identifier: Apache-2.0

log: true

inputs:
  nats-input:
    type: input
    address: nats:4222
    subject: telemetry
    outputs:
      - influxdb-output

outputs:
  influxdb-output:
    type: influxdb
    url: http://influxdb:8086
    bucket: telemetry # db name
    token: gnmic:gnmic # username:password
    batch-size: 1000
    flush-timer: 10s