# © 2022 Nokia.
#
# This code is a Contribution to the gNMIc project (“Work”) made under the Google Software Grant and Corporate Contributor License Agreement (“CLA”) and governed by the Apache License 2.0.
# No other rights or licenses in or to any of Nokia’s intellectual property are granted for any other purpose.
# This code is provided on an “as is” basis without any warranties of any kind.
#
# SPDX-License-Identifier: Apache-2.0

version: '3' 

networks:
  gnmic-net:
    driver: bridge

services:
  gnmic1:
    image: ghcr.io/karimra/gnmic:latest
    container_name: gnmic1
    volumes:
      - ./gnmic1.yaml:/app/gnmic.yaml
    command: "subscribe --config /app/gnmic.yaml"
    networks:
      - gnmic-net
    depends_on:
      - nats
      
  nats:
    image: 'nats:latest'
    container_name: nats
    networks:
      - gnmic-net    
    ports:
      - "4222:4222"
      - "6222:6222"
      - "8222:8222"
      